language: go
sudo: true
dist: trusty

go:
  - 1.8

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libvirt-dev

install:
  - go get github.com/tools/godep
  - go get github.com/stretchr/testify
  - godep restore

script:
  - bash test.sh

after_success:
  - go install ./core0
  - go install ./coreX
  - bash <(curl -s https://codecov.io/bash)
