matrix:
  include: 
    - language: python
      python: 3.5
      before_script:
        - pip3 install -r tests/requirements.txt
        - pip3 install client/py-client/.
        - pip3 install git+https://github.com/gigforks/packet-python.git
      script:
        - cd tests; nosetests -v -s  testsuite/a_basic/tests_01_system.py:SystemTests.test001_execute_commands 
    
    - language: go
      sudo: true
      dist: trusty
      go: 1.8
      before_install:
        - sudo apt-get -qq update
        - sudo apt-get install -y libvirt-dev libcap-dev
      install:
        - go get github.com/stretchr/testify
      script:
        - bash test.sh
      after_success:
        - go install ./core0
        - go install ./coreX
        - bash <(curl -s https://codecov.io/bash)

