matrix:
  include:
    - language: python
      python: 3.5
      if: type IN (api, cron)
      install:
        - sudo bash tests/install_jumpscale.sh
      script:
        - python3 tests/env_setup_run.py --zos_ip $ZOS_ip --zerotierid $ZT_NET_ID --branch $BRANCH --zt_token $ZT_TOKEN


    - language: go
      sudo: true
      dist: trusty
      go: 1.8
      before_install:
        - sudo apt-get -qq update
        - sudo apt-get install -y libvirt-dev libcap-dev
      install:
        - go get github.com/stretchr/testify
      script:
        - bash test.sh
      after_success:
        - go install ./core0
        - go install ./coreX
        - bash <(curl -s https://codecov.io/bash)
