matrix:
  include:
    - language: python
      sudo: true
      dist: trusty
      python: 3.5
      if: type IN (api, cron)
      before_install:
        - sudo apt-get install -y python3.5 python3.5-dev
        - sudo rm -f /usr/bin/python
        - sudo rm -f /usr/bin/python3
        - sudo ln -s /usr/bin/python3.5 /usr/bin/python
        - sudo ln -s /usr/bin/python3.5 /usr/bin/python3
      install:
        - sudo bash tests/install_zt_js.sh
      script:
        - sudo python3 tests/env_setup_run.py --zos_ip $ZOS_ip --zerotierid $ZT_NET_ID --branch $BRANCH --zt_token $ZT_TOKEN


    - language: go
      sudo: true
      dist: trusty
      go: 1.8
      before_install:
        - sudo apt-get -qq update
        - sudo apt-get install -y libvirt-dev libcap-dev
      install:
        - go get github.com/stretchr/testify
      script:
        - bash test.sh
      after_success:
        - go install ./core0
        - go install ./coreX
        - bash <(curl -s https://codecov.io/bash)
