language: go

go:
  - 1.7.1

install:
  - go get github.com/tools/godep
  - go get github.com/stretchr/testify
  - godep restore

script:
  - bash test.sh

after_success:
  - go install ./core0
  - go install ./coreX
  - bash <(curl -s https://codecov.io/bash)
