matrix:
  include:
    - language: python
      sudo: true
      dist: trusty
      python: 3.5
      if: type IN (api, cron)
      install:
        - source tests/before_script
        - sudo bash tests/install_zt_js.sh
      before_script:
        - sudo python3 -u tests/env_setup_run.py --zos_ip $ZOS_ip --zerotierid $ZT_NET_ID --branch $BRANCH --zt_token $ZT_TOKEN
      script:
        - sudo python3 -u tests/run_tests --zos_ip $ZOS_ip
      after_script:
        - sudo python3 -u tests/run_tests --teardown


    - language: go
      sudo: true
      dist: trusty
      go: 1.8
      before_install:
        - sudo apt-get -qq update
        - sudo apt-get install -y libvirt-dev libcap-dev
      install:
        - go get github.com/stretchr/testify
      script:
        - bash test.sh
      after_success:
        - go install ./core0
        - go install ./coreX
        - bash <(curl -s https://codecov.io/bash)
