[startup.syslogd]
name = "core.system"

[startup.syslogd.args]
name = "syslogd"
args = ["-n", "-O", "/var/log/messages"]

[startup.klogd]
name = "core.system"

[startup.klogd.args]
name = "klogd"
args = ["-n"]
