[extension."disk.list"]
binary = "sh"
args = ["-c", "echo 20::: && lsblk -J -b && echo :::"]

[extension."disk.getpart"]
binary = "sh"
args = ["-c", """
set -e
echo 20:::
START=$(cat /sys/block/{disk}/{part}/start)
SIZE=$(cat /sys/block/{disk}/{part}/size)
BLOCKSIZE=$(lsblk -n -r -o PHY-SEC /dev/{part})
START=$(($START*$BLOCKSIZE))
SIZE=$(($SIZE*$BLOCKSIZE))

cat <<EOF
{
    \"blocksize\": ${BLOCKSIZE},
    \"start\": ${START},
    \"size\": ${SIZE}
}
EOF
echo :::
"""]

[extension."disk.mktable"]
binary = "parted"
args = ["/dev/{disk}", "mktable", "{table_type}"]

[extension."disk.mkpart"]
binary = "parted"
args = ["/dev/{disk}", "mkpart", "{part_type}", "{start}", "{end}"]

[extension."disk.rmpart"]
binary = "parted"
args = ["/dev/{disk}", "rm", "{number}"]

[extension."disk.mount"]
binary = "mount"
args = ["-o", "{options}", "{source}", "{target}"]

[extension."disk.umount"]
binary = "umount"
args = ["{source}"]

