[startup.libvirt]
name = "core.system"
protected = true

[startup.libvirt.args]
name = "libvirtd"
args = ["--listen"]

[startup.virtlogd]
name = "core.system"
protected = true

[startup.virtlogd.args]
name = "virtlogd"
