#WARNING:
# This redis instance is required for core0/coreX communication and must not be removed or modified unless you really really
# know what you are doing.
#
# Code assumes that this socket is available in the given location

[startup."redis.public"]
name = "core.system"
running_match = "The server is now ready to accept connections"
protected = true

[startup."redis.public".args]
name = "redis-server"
args = ["--unixsocket", "/var/run/redis.socket", "--bind", "0.0.0.0", "--port", "6379"]