[startup.redis]
name = "core.system"
after = ["init"]
protected = true

[startup.redis.args]
name = "redis-server"
args = [
    "--port", "6379",
    "--bind", "0.0.0.0",
    "--protected-mode", "no"
]
