# Start the zerotier daemon, after the networking is already configured
[startup.zerotier]
name = "core.system"
after = ["net"]
protected = true

[startup.zerotier.args]
name = "zerotier-one"
args = ["/tmp/core-0-zt"]

[extension."zerotier.join"]
binary = "zerotier-cli"
args = ["-D/tmp/core-0-zt", "join", "{network}"]

[extension."zerotier.leave"]
binary = "zerotier-cli"
args = ["-D/tmp/core-0-zt", "leave", "{network}"]

[extension."zerotier.list"]
binary = "sh"
args = ["-c", "echo 20::: && zerotier-cli -D/tmp/core-0-zt listnetworks -j && echo :::"]

[extension."zerotier.info"]
binary = "sh"
args = ["-c", "echo 20::: && zerotier-cli -D/tmp/core-0-zt info -j && echo :::"]

[startup.zerotierkernel]
name = "zerotier.join"
after = ["zerotier"]

[startup.zerotierkernel.args]
network = "{zerotier}"
