#leave /tmp and /opt/jumpscale8 in this file, gets replaced during installation

[main]
max_jobs = 200
include = ["/root/conf"]
log_level = "debug"
# network = "./network.toml"

[sink.main]
url = "redis://127.0.0.1:6379"
password = ""

[logging]
    [logging.db]
    type = "DB"
    address = "/var/log/g8os"
    levels = [2, 4, 7, 8, 9, 11]  # (all error messages + debug) empty for all

    [logging.console]
    type = "console"
    levels = [1, 2, 4, 7, 8, 9]
	
	[logging.redis]
	type = "redis"
	levels = [1, 2, 4, 7, 8, 9]
	address = "127.0.0.1:6379"
	batch_size = 1000


[stats]
interval = 60000 # milliseconds (1 min)

[stats.redis]
enabled = true
flush_interval = 10 # seconds
address = "127.0.0.1:6379"

[globals]
fuse_storage = "ardb://home.maxux.net:26379"
